name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thank you for poiting out this issue! Maintainers will look into this as early as possible.'
        pr-message: 'Woohoo! Congrats on submitting PR and making an enhancement in the webapp.'
